name: uamishop-app

services:
  mysql-catalogo:
    image: mysql:latest
    container_name: uamishop-mysql-catalogo
    environment:
      MYSQL_DATABASE: uamishop_catalogo
      MYSQL_USER: uamishop
      MYSQL_PASSWORD: uamishop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3308:3306' # Mapea el puerto 3306 del contenedor al puerto 3308 en el host para evitar conflictos con MySQL local
    volumes:
      - mysql_catalogo_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  mysql-ordenes:
    image: mysql:latest
    container_name: uamishop-mysql-ordenes
    environment:
      MYSQL_DATABASE: uamishop_ordenes
      MYSQL_USER: uamishop
      MYSQL_PASSWORD: uamishop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3309:3306' # Mapea el puerto 3306 del contenedor al puerto 3309 en el host para evitar conflictos con MySQL local
    volumes:
      - mysql_ordenes_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  mysql-ventas:
    image: mysql:latest
    container_name: uamishop-mysql-ventas
    environment:
      MYSQL_DATABASE: uamishop_ventas
      MYSQL_USER: uamishop
      MYSQL_PASSWORD: uamishop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3310:3306' # Mapea el puerto 3306 del contenedor al puerto 3310 en el host para evitar conflictos con MySQL local
    volumes:
      - mysql_ventas_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  uamishop-catalogo:
    build:
      context: uamishop-catalogo/
      dockerfile: Dockerfile
    image: uamishop-catalogo:latest
    container_name: uamishop-catalogo
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      NODE_ENV: mysql
      DB_HOST: mysql-catalogo
      DB_PORT: 3306
      DB_DATABASE: uamishop_catalogo
      DB_USERNAME: uamishop
      DB_PASSWORD: uamishop
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mysql-catalogo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  uamishop-ventas:
    build:
      context: uamishop-ventas/
      dockerfile: Dockerfile
    image: uamishop-ventas:latest
    container_name: uamishop-ventas
    ports:
      - '8082:8082'
    environment:
      PORT: 8082
      NODE_ENV: mysql
      DB_HOST: mysql-ventas
      DB_PORT: 3306
      DB_DATABASE: uamishop_ventas
      DB_USERNAME: uamishop
      DB_PASSWORD: uamishop
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      CATALOGO_SERVICE_URL: http://uamishop-catalogo:8081
    depends_on:
      mysql-ventas:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  uamishop-ordenes:
    build:
      context: uamishop-ordenes/
      dockerfile: Dockerfile
    image: uamishop-ordenes:latest
    container_name: uamishop-ordenes
    ports:
      - '8083:8083'
    environment:
      PORT: 8083
      NODE_ENV: mysql
      DB_HOST: mysql-ordenes
      DB_PORT: 3306
      DB_DATABASE: uamishop_ordenes
      DB_USERNAME: uamishop
      DB_PASSWORD: uamishop
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      VENTAS_SERVICE_URL: http://uamishop-ventas:8082
    depends_on:
      mysql-ordenes:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: uamishop-rabbitmq
    ports:
      - '5672:5672' # Puerto para la comunicación con RabbitMQ
      - '15672:15672' # Puerto para la interfaz de administración de RabbitMQ
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

volumes:
  mysql_catalogo_data:
  mysql_ordenes_data:
  mysql_ventas_data:
