export enum EstadoOrden{
    PENDIENTE = 'PENDIENTE',
    CONFIRMADA = 'CONFIRMADA',
    PAGO_PROCESADO = 'PAGO_PROCESADO',
    EN_PREPARACION = 'EN_PREPARACION',
    ENVIADA= 'ENVIADA',
    EN_TRANSITO = 'EN_TRANSITO',
    ENTREGADA = 'ENTREGADA',
    CANCELADA = 'CANCELADA'
}
